### ISSUE TITLE
can not use

### ISSUE THREAD

**Issue by xiaoqianghaochi** [mmdapl/egg-axios-plus#1]
this.ctx.axios is undefined

**Comment by mmdapl** [comment]
keep try or give me a example for you question !

**Comment by terrence-c** [comment]
I have the similar problem. Following the official eggjs quickstart guide  https://eggjs.org/en/intro/quickstart.html , I replaced the curl request with this:
```
const { data: idList } = await this.ctx.axios.get(
      `${serverUrl}/topstories.json`,
      {
        orderBy: '"$key"',
        startAt: `"${pageSize * (page - 1)}"`,
        endAt: `"${pageSize * page - 1}"`,
      }
    );
```

I notice when I start the server, there is a warning:
`WARN 1093 [egg:loader] pluginName(axios) is different from pluginConfigName(egg-axios-plus)`

**Comment by mmdapl** [comment]
@xiaoqianghaochi @terrence-c 
Please run the bash ` npm install egg-axios-plus@latest --save`  and update the latest version of egg-axios-plus, your problem will be solved, if you have doubts during the use, I believe the rich documentation will help you, thank you for using

**Comment by mmdapl** [comment]
@terrence-c  don`t know if your problem about egg-axios-plus is solved, if still existed , can tell me ,i close this issues first....

**Comment by terrence-c** [comment]
It works perfectly now, thank you!
