### ISSUE TITLE
responseType: 'stream' 情况下报错

### ISSUE THREAD

**Issue by blueforest** [mmdapl/egg-axios-plus#6]
在node端使用
`   Axios.get(imgUrl, {
      responseType: 'stream'
    }).then(res => {
      res.pipe(writeStream)
    }).catch(e => {
      console.log('eeee', e)
    })`
会报错: ` TypeError: Converting circular structure to JSON `，只能手动加一个responseInterceptorsHandler

建议axios_request 49 行 ` ${JSON.stringify(response.data)} ` 加一个判断 if (response.config.responseType === 'stream') {}

**Comment by mmdapl** [comment]
ok，更新到最新版本即可
